# Seminar 10

## Knowledge Distillation

In [ ]:
!pip install transformers==4.45.2 sentence-transformers==3.1.1
!pip install evaluate

Collecting transformers==4.45.2
  Downloading transformers-4.45.2-py3-none-any.whl.metadata (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.4/44.4 kB 2.9 MB/s eta 0:00:00
Collecting sentence-transformers==3.1.1
  Downloading sentence_transformers-3.1.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers==4.45.2) (3.17.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /usr/local/lib/python3.11/dist-packages (from transformers==4.45.2) (0.28.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers==4.45.2) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers==4.45.2) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers==4.45.2) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers==4.45.2) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers==4.45.2) (2.32.3)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from transformers==4.45.2) (0.5.3)
Collecting tokenizers<0.21,>=0.20 (from transformers==4.45.2)
  Downloading tokenizers-0.20.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers==4.45.2) (4.67.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers==3.1.1) (2.6.0+cu124)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (from sentence-transformers==3.1.1) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from sentence-transformers==3.1.1) (1.14.1)
Requirement already satisfied: Pillow in /usr/local/lib/python3.11/dist-packages (from sentence-transformers==3.1.1) (11.1.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.45.2) (2024.10.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.45.2) (4.12.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers==3.1.1) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers==3.1.1) (3.1.6)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers==3.1.1)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers==3.1.1)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers==3.1.1)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch>=1.11.0->sentence-transformers==3.1.1)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch>=1.11.0->sentence-transformers==3.1.1)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch>=1.11.0->sentence-transformers==3.1.1)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch>=1.11.0->sentence-transformers==3.1.1)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch>=1.11.0->sentence-transformers==3.1.1)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch>=1.11.0->sentence-transformers==3.1.1)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers==3.1.1) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers==3.1.1) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers==3.1.1) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers==3.1.1)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers==3.1.1) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers==3.1.1) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers==3.1.1) (1.3.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers==4.45.2) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers==4.45.2) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers==4.45.2) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers==4.45.2) (2025.1.31)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->sentence-transformers==3.1.1) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->sentence-transformers==3.1.1) (3.6.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers==3.1.1) (3.0.2)
Downloading transformers-4.45.2-py3-none-any.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 71.5 MB/s eta 0:00:00
Downloading sentence_transformers-3.1.1-py3-none-any.whl (245 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 245.3/245.3 kB 17.0 MB/s eta 0:00:00
Downloading tokenizers-0.20.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 52.0 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 3.8 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 38.2 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 22.5 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 34.1 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.5 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 4.2 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 16.9 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 8.1 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 6.0 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 96.8 MB/s eta 0:00:00
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, tokenizers, nvidia-cusolver-cu12, transformers, sentence-transformers
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.21.1
    Uninstalling tokenizers-0.21.1:
      Successfully uninstalled tokenizers-0.21.1
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
  Attempting uninstall: transformers
    Found existing installation: transformers 4.48.3
    Uninstalling transformers-4.48.3:
      Successfully uninstalled transformers-4.48.3
  Attempting uninstall: sentence-transformers
    Found existing installation: sentence-transformers 3.4.1
    Uninstalling sentence-transformers-3.4.1:
      Successfully uninstalled sentence-transformers-3.4.1
Successfully installed nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127 sentence-transformers-3.1.1 tokenizers-0.20.3 transformers-4.45.2
Requirement already satisfied: evaluate in /usr/local/lib/python3.11/dist-packages (0.4.3)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from evaluate) (3.4.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.11/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.32.3)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.11/dist-packages (from evaluate) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from evaluate) (3.5.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.11/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2024.10.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from evaluate) (0.28.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from evaluate) (24.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (3.17.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (3.11.13)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (6.0.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2025.1)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (0.3.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.18.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)

In [ ]:
student_id = "google/bert_uncased_L-2_H-128_A-2"
teacher_id = "textattack/bert-base-uncased-SST-2"

Check that tokenizers are the same

In [ ]:
from transformers import AutoTokenizer

teacher_tokenizer = AutoTokenizer.from_pretrained(teacher_id)
student_tokenizer = AutoTokenizer.from_pretrained(student_id)

sample = "This is a basic example, with different words to test."

assert teacher_tokenizer(sample) == student_tokenizer(sample)

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

In [ ]:
sample = "I love pizza"

assert teacher_tokenizer(sample) == student_tokenizer(sample)

data

In [ ]:
!pip install datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.11/dist-packages (3.4.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets) (3.17.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.11/dist-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2024.12.0,>=2023.1.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<=2024.12.0,>=2023.1.0->datasets) (2024.10.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets) (3.11.13)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (0.3.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.18.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [ ]:
from datasets import load_dataset

dataset_id="glue"
dataset_config="sst2"

dataset = load_dataset(dataset_id, dataset_config)
dataset

DatasetDict({
    train: Dataset({
        features: ['sentence', 'label', 'idx'],
        num_rows: 67349
    })
    validation: Dataset({
        features: ['sentence', 'label', 'idx'],
        num_rows: 872
    })
    test: Dataset({
        features: ['sentence', 'label', 'idx'],
        num_rows: 1821
    })
})

In [ ]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(teacher_id)

def process(examples):
    tokenized_inputs = tokenizer(
        examples["sentence"], truncation=True, max_length=512
    )
    return tokenized_inputs

tokenized_datasets = dataset.map(process, batched=True)
tokenized_datasets = tokenized_datasets.rename_column("label","labels")

tokenized_datasets["test"].features

Map:   0%|          | 0/67349 [00:00<?, ? examples/s]

Map:   0%|          | 0/872 [00:00<?, ? examples/s]

Map:   0%|          | 0/1821 [00:00<?, ? examples/s]

{'sentence': Value(dtype='string', id=None),
 'labels': ClassLabel(names=['negative', 'positive'], id=None),
 'idx': Value(dtype='int32', id=None),
 'input_ids': Sequence(feature=Value(dtype='int32', id=None), length=-1, id=None),
 'token_type_ids': Sequence(feature=Value(dtype='int8', id=None), length=-1, id=None),
 'attention_mask': Sequence(feature=Value(dtype='int8', id=None), length=-1, id=None)}

In [ ]:
from transformers import TrainingArguments, Trainer
import torch
import torch.nn as nn
import torch.nn.functional as F

class DistillationTrainingArguments(TrainingArguments):
    def __init__(self, *args, alpha=0.5, temperature=2.0, **kwargs):
        super().__init__(*args, **kwargs)

        #instead of 1 - lambda
        self.alpha = alpha
        self.temperature = temperature

class DistillationTrainer(Trainer):
    def __init__(self, *args, teacher_model=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.teacher = teacher_model
        #Teacher and students are on cpu/gpu
        self._move_model_to_device(self.teacher,self.model.device)
        self.teacher.eval()

    def compute_loss(self, student, inputs, return_outputs=False):

        #L_student
        outputs_student = student(**inputs)
        student_loss = outputs_student.loss

        #res of teacher
        with torch.no_grad():
          outputs_teacher = self.teacher(**inputs)


        #softmax with T, L_distillation
        loss_function = nn.KLDivLoss(reduction="batchmean")
        loss_logits = (loss_function(
            F.log_softmax(outputs_student.logits / self.args.temperature, dim=-1),
            F.softmax(outputs_teacher.logits / self.args.temperature, dim=-1)) * (self.args.temperature ** 2))
        #final loss
        loss = self.args.alpha * student_loss + (1. - self.args.alpha) * loss_logits
        return (loss, outputs_student) if return_outputs else loss

In [ ]:
from transformers import AutoModelForSequenceClassification, DataCollatorWithPadding


labels = tokenized_datasets["train"].features["labels"].names
num_labels = len(labels)
label2id, id2label = dict(), dict()
for i, label in enumerate(labels):
    label2id[label] = str(i)
    id2label[str(i)] = label


training_args = DistillationTrainingArguments(
    num_train_epochs=7,
    per_device_train_batch_size=128,
    per_device_eval_batch_size=128,
    fp16=True,
    learning_rate=6e-5,
    seed=0,
    output_dir="distillation",
    logging_strategy="epoch", # to get more information to TB
    evaluation_strategy="epoch",
    save_strategy="epoch",
    save_total_limit=2,
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    report_to="tensorboard",
    # distilation parameters
    alpha=0.5,
    temperature=4.0
    )


data_collator = DataCollatorWithPadding(tokenizer=tokenizer)


teacher_model = AutoModelForSequenceClassification.from_pretrained(
    teacher_id,
    num_labels=num_labels,
    id2label=id2label,
    label2id=label2id,
)


student_model = AutoModelForSequenceClassification.from_pretrained(
    student_id,
    num_labels=num_labels,
    id2label=id2label,
    label2id=label2id,
)

/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1545: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google/bert_uncased_L-2_H-128_A-2 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [ ]:
teacher_model.num_parameters()

109483778

In [ ]:
student_model.num_parameters()

4386178

In [ ]:
teacher_model.num_parameters() / student_model.num_parameters()

24.961088674467838

In [ ]:
!pip install evaluate

In [ ]:
from evaluate import load
import numpy as np

# define metrics and metrics function
accuracy_metric = load( "accuracy")

def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)
    acc = accuracy_metric.compute(predictions=predictions, references=labels)
    return {
        "accuracy": acc["accuracy"],
    }

In [ ]:
trainer = DistillationTrainer(
    student_model,
    training_args,
    teacher_model=teacher_model,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"],
    data_collator=data_collator,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics,
)

In [ ]:
trainer.train()

KeyboardInterrupt:

In [ ]:
31 * 60 / 18

103.33333333333333

## Quantization

In [ ]:
import torch

class M(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.fc = torch.nn.Linear(4, 4)

    def forward(self, x):
        x = self.fc(x)
        return x


model_fp32 = M()

model_int8 = torch.ao.quantization.quantize_dynamic(
    model_fp32,
    {torch.nn.Linear},  # a set of layers to dynamically quantize
    dtype=torch.qint8)  # the target dtype for quantized weights


input_fp32 = torch.randn(4, 4, 4, 4)
res = model_int8(input_fp32)

In [ ]:
model_fp32.fc.weight.dtype

torch.float32

In [ ]:
model_int8.fc.weight().dtype

torch.qint8

In [ ]:
model_int8(input_fp32)[0][0]

tensor([[-0.5778, -0.8731,  1.2256,  0.3517],
        [-0.5516, -0.1853,  0.6113, -0.7420],
        [ 1.5896, -0.3849, -0.2877,  0.5785],
        [ 1.5851, -1.6432,  0.1357,  0.4307]])

In [ ]:
model_fp32(input_fp32)[0][0]

tensor([[-0.5735, -0.8831,  1.2303,  0.3502],
        [-0.5462, -0.1728,  0.6044, -0.7509],
        [ 1.5861, -0.4018, -0.2802,  0.5938],
        [ 1.5781, -1.6371,  0.1355,  0.4281]], grad_fn=<SelectBackward0>)

## LoRA

Sample eample of LoRA from [tutorial](https://pytorch.org/torchtune/0.4/tutorials/lora_finetune.html)

In [ ]:
import torch
from torch import nn

class LoRALinear(nn.Module):
  def __init__(
    self,
    in_dim: int,
    out_dim: int,
    rank: int,
    alpha: float
  ):
    super().__init__()
    # These are the weights from the original pretrained model
    self.linear = nn.Linear(in_dim, out_dim, bias=False)

    # These are the new LoRA params. In general rank << in_dim, out_dim
    self.lora_a = nn.Linear(in_dim, rank, bias=False)
    self.lora_b = nn.Linear(rank, out_dim, bias=False)

    # Rank and alpha are commonly-tuned hyperparameters
    self.rank = rank
    self.alpha = alpha


    # The original params are frozen, and only LoRA params are trainable.
    self.linear.weight.requires_grad = False
    self.lora_a.weight.requires_grad = True
    self.lora_b.weight.requires_grad = True

  def forward(self, x: torch.Tensor) -> torch.Tensor:
    # This would be the output of the original model
    frozen_out = self.linear(x)

    # lora_a projects inputs down to the much smaller self.rank,
    # then lora_b projects back up to the output dimension
    lora_out = self.lora_b(self.lora_a(x))

    # Finally, scale by the alpha parameter (normalized by rank)
    # and add to the original model's outputs
    return frozen_out + (self.alpha / self.rank) * lora_out

In [ ]:
l = LoRALinear(in_dim = 100,
    out_dim = 200,
    rank = 5,
    alpha = 1)

In [ ]:
#no grad
l.lora_a.weight.grad, l.linear.weight.grad

(None, None)

In [ ]:
input = torch.randn(8, 100)
l(input).shape

torch.Size([8, 200])

In [ ]:
l.linear.weight

Parameter containing:
tensor([[-0.0461,  0.0366, -0.0911,  ..., -0.0075, -0.0596,  0.0659],
        [ 0.0716,  0.0439, -0.0191,  ..., -0.0108,  0.0698,  0.0196],
        [-0.0434, -0.0212, -0.0336,  ...,  0.0518, -0.0574,  0.0684],
        ...,
        [ 0.0734, -0.0984, -0.0614,  ..., -0.0241, -0.0586,  0.0347],
        [-0.0756,  0.0997,  0.0374,  ...,  0.0063,  0.0182,  0.0200],
        [ 0.0520,  0.0948, -0.0148,  ..., -0.0125,  0.0396,  0.0397]])

In [ ]:
l.lora_a.weight

Parameter containing:
tensor([[-9.6061e-02,  2.1875e-02, -5.7947e-02, -7.1107e-02,  9.2177e-02,
          3.1203e-02, -2.6312e-03, -6.3715e-03, -8.0794e-02,  4.1306e-02,
          4.8830e-02,  2.5378e-02,  6.7480e-02, -9.0064e-02, -2.4844e-03,
         -5.2810e-02, -5.1469e-02,  2.9085e-02, -1.2664e-02,  4.7804e-02,
         -5.5797e-02,  7.1353e-02,  9.4586e-02, -8.6629e-02,  6.3589e-02,
         -1.0987e-02, -1.5587e-03,  4.1777e-02,  8.6642e-03, -3.2101e-02,
          5.7200e-02,  2.6291e-02,  5.7288e-02, -1.6251e-02,  4.7508e-02,
          1.5544e-02, -9.0908e-02, -7.2360e-03,  7.1015e-02, -9.6398e-02,
         -9.0636e-02, -9.5219e-02,  9.5801e-02, -4.3064e-02, -4.9587e-02,
         -3.6388e-02,  7.6211e-02, -3.2581e-02, -8.9136e-02,  3.7001e-02,
          3.9806e-02, -2.8935e-02,  4.7723e-02, -3.7376e-02,  1.8203e-02,
          3.9763e-02, -7.3347e-02, -8.3479e-02, -6.2022e-02, -2.4372e-02,
          3.0558e-02, -4.3462e-02,  4.3430e-02, -2.4443e-02, -4.3101e-02,
          9.2503e-02,  8.5277e-02, -2.1389e-02,  8.5997e-02,  9.1147e-02,
          5.7007e-02,  3.9048e-02, -1.0797e-02,  1.5626e-02,  2.3150e-02,
         -4.6480e-02,  8.2018e-02,  3.8168e-02,  5.3670e-02,  1.8644e-02,
          1.0897e-02,  8.1306e-03, -2.0115e-02,  8.0150e-02,  7.1058e-02,
         -3.2412e-02,  2.5794e-02,  3.2750e-02, -8.5341e-02,  6.5088e-02,
         -5.6332e-02,  5.5725e-02,  7.1524e-02,  7.5326e-02, -6.1955e-02,
         -8.4375e-02, -3.1532e-02,  5.6099e-02, -1.3501e-02,  3.7052e-02],
        [ 3.1346e-02, -4.7890e-02, -6.6036e-02, -1.1904e-03, -2.6009e-02,
         -5.1544e-02, -9.7722e-02, -1.4676e-02,  6.8336e-02, -4.6653e-02,
          7.9975e-03, -6.3935e-02,  7.9651e-02, -2.1006e-02,  9.5033e-02,
          3.2215e-02,  4.8914e-02,  1.3391e-02,  9.0449e-02, -5.3926e-02,
          8.8092e-02, -9.7922e-03, -4.5119e-02,  7.0182e-02,  4.8891e-02,
          6.9041e-02, -5.1420e-02, -1.7622e-02, -2.8392e-02, -8.9901e-02,
         -2.7851e-02,  6.3491e-02,  8.8610e-02, -8.4038e-02, -8.8768e-02,
          6.2394e-02,  6.6132e-02,  3.1930e-02, -7.3880e-02,  2.8905e-02,
         -1.9117e-02, -2.9397e-02, -9.8123e-02,  1.8015e-02,  4.4440e-02,
         -8.9417e-02,  8.8511e-02, -1.3935e-03, -4.5111e-02, -3.7483e-02,
         -2.1463e-03, -5.4446e-02, -5.2682e-02,  4.2141e-03, -2.7101e-02,
          7.2192e-02, -2.5850e-02,  9.4917e-02, -3.2673e-02, -8.7835e-02,
         -3.2314e-02,  5.7323e-03, -9.4540e-02, -5.3599e-02,  8.6548e-02,
         -7.7453e-02, -4.0547e-02, -6.1902e-03,  5.4606e-02, -4.7085e-02,
         -7.5587e-02,  7.0747e-02, -1.1919e-02, -9.3012e-02, -6.1295e-02,
          9.8219e-03, -5.6202e-02, -3.9454e-02,  6.3570e-02, -6.7742e-02,
          3.7330e-02, -2.5138e-02,  6.0862e-03, -9.1390e-02, -9.6487e-02,
          4.5199e-02,  7.6015e-02, -9.1594e-02,  4.1732e-02, -7.2979e-02,
         -4.2812e-02,  7.3111e-02,  7.9176e-02, -2.7436e-02,  1.9116e-02,
          1.5038e-02, -3.2114e-02,  9.7222e-03, -7.1712e-02,  3.8658e-02],
        [ 3.1868e-03, -3.5128e-02, -5.4163e-02, -4.2504e-02,  3.0115e-02,
          9.6673e-02,  9.1854e-02, -1.9640e-02, -8.2856e-02,  7.6090e-02,
         -3.6616e-02,  2.5301e-02,  8.3901e-02, -7.5091e-02, -8.2480e-02,
         -2.9505e-02,  9.3869e-02,  1.0965e-02, -7.6056e-02,  8.5665e-02,
          4.7869e-02, -4.5411e-02, -3.6375e-02,  3.0647e-02,  1.1785e-03,
         -4.0121e-02, -7.9874e-02, -5.2595e-02, -6.1554e-03,  6.6025e-02,
         -2.9918e-02,  7.7420e-02, -9.0538e-02, -8.8193e-03, -1.1006e-02,
         -1.7764e-02, -9.9436e-02, -8.9023e-02, -7.5149e-02, -9.4088e-02,
          1.5020e-03,  6.2714e-02,  5.7388e-02,  1.7160e-02,  6.6188e-02,
         -3.3295e-02,  4.4121e-02, -1.6275e-02,  8.7991e-02, -6.4074e-02,
         -2.8230e-02, -8.5839e-02, -4.0992e-04, -3.3161e-02, -6.0635e-02,
          5.7068e-02, -4.4994e-02, -8.9903e-02, -7.5398e-02,  5.4565e-03,
          5.6459e-02,  2.3087e-03,  5.1648e-02, -8.8160e-02, -3.6350e-02,
         -5.4125e-02, -2.4567e-02, -8.0204e-02, -4.1479e-02,  9.0780e-02,
         -7.3089e-02, -7.6975e-02,  3.9051e-02, -5.1114e-02,  1.4975e-02,
          4.1631e-02, -4.5643e-02,  9.4932e-02, -1.9240e-02, -9.6719e-02,
          8.8844e-02,  5.2176e-02,  9.3136e-02,  5.5012e-02, -9.7078e-02,
         -3.4631e-02, -7.3425e-02, -6.6086e-02,  2.3393e-02,  6.4176e-02,
         -4.9729e-02, -2.6798e-02, -4.2009e-02,  5.1637e-02, -3.5969e-02,
          5.9764e-02, -2.7511e-03,  3.7399e-03, -6.0526e-02, -5.4884e-02],
        [ 1.0310e-02,  1.4505e-02,  2.6164e-02, -6.0138e-02,  5.6768e-02,
         -7.8531e-03, -9.8288e-02,  9.3112e-02, -6.9321e-02,  7.3572e-02,
         -1.7306e-02,  5.6554e-02, -8.7767e-02,  2.6765e-02, -9.6716e-02,
          6.8159e-02,  5.9017e-03, -9.6604e-02,  8.8937e-02,  8.7876e-02,
         -9.7213e-02,  3.3315e-02, -4.0383e-02, -9.7469e-02, -4.7865e-02,
         -3.9571e-03,  8.2541e-02, -1.3244e-03,  4.0945e-02, -9.5451e-02,
          3.3099e-02, -9.5232e-02,  2.2067e-02,  3.1998e-03,  3.8234e-02,
         -3.6920e-02,  9.7615e-02,  1.3890e-02, -7.7895e-02,  3.0578e-02,
          5.4640e-02,  7.4010e-02, -2.9947e-03, -5.4693e-03, -9.0639e-02,
          3.6779e-02, -6.2674e-02, -1.9265e-02,  8.2998e-02, -8.1857e-02,
          1.4002e-02, -2.1223e-03,  3.8907e-02, -2.4873e-02,  7.9602e-02,
          5.0907e-02, -6.1939e-02,  7.8580e-02,  8.9663e-02, -7.6292e-03,
          8.9540e-02,  8.6126e-02, -5.2286e-03, -8.4983e-03,  7.8910e-02,
          7.9713e-03,  4.7189e-02, -4.5326e-02, -7.9438e-02,  4.1812e-02,
          8.1418e-02, -8.0500e-02,  7.8727e-02,  2.6640e-02, -5.2774e-05,
          5.9750e-02,  4.0605e-02,  6.7617e-02,  6.6540e-02, -3.2035e-02,
          4.3308e-02,  5.6042e-02, -9.0792e-02, -2.8694e-02,  3.2521e-02,
         -1.2450e-02,  1.7115e-02, -6.0765e-02, -9.8305e-02, -6.1393e-02,
         -9.1814e-02,  9.4505e-02, -5.5620e-02, -8.3167e-02,  3.3495e-02,
         -1.4243e-02, -2.5109e-02, -6.7728e-02,  9.3183e-02, -1.7321e-02],
        [-6.3036e-02, -5.8481e-02,  4.1149e-02,  7.4483e-02,  4.9050e-02,
          4.8842e-02,  7.7090e-02, -7.8298e-03, -7.0994e-02, -2.6193e-02,
         -1.2290e-03, -9.2803e-02,  8.0002e-02, -9.2548e-03, -8.1826e-02,
          2.8417e-02, -3.0235e-02, -8.6012e-02,  1.3086e-02,  1.1707e-02,
         -2.0437e-03, -5.8364e-04, -5.3346e-02,  2.2984e-02, -2.5545e-02,
          4.1063e-02, -5.0820e-02, -4.1106e-03, -7.6660e-02,  9.4873e-03,
          4.2249e-02, -8.0321e-03,  4.7816e-02, -8.5441e-02,  1.2617e-02,
          3.3461e-02,  8.2599e-02, -8.5207e-02, -5.5910e-02, -8.2988e-02,
         -5.1354e-02, -3.8813e-02, -2.0769e-02, -2.0455e-02,  9.5058e-02,
         -6.6830e-02,  6.2861e-02,  8.2167e-02,  2.7576e-02, -7.3152e-03,
          8.0046e-02,  3.5271e-02, -9.4084e-02, -7.8400e-02, -9.1244e-02,
         -5.8362e-02, -2.8962e-02, -8.4311e-02,  7.6824e-02,  7.7283e-03,
          3.7209e-03,  8.4774e-02,  6.9949e-02, -2.9220e-02, -4.1548e-02,
          9.3794e-02,  6.5697e-02, -1.4476e-03, -2.6068e-02,  7.2740e-03,
         -3.5340e-02,  1.9113e-02, -9.8997e-02, -2.1347e-02,  4.2983e-02,
         -9.3196e-02,  3.5984e-02, -6.1008e-02,  2.9523e-02, -4.4994e-02,
          8.5793e-02, -5.5168e-03, -4.8615e-02,  9.3471e-02, -6.7709e-02,
         -4.2876e-02,  5.3405e-02, -3.2548e-02, -6.4827e-02, -4.5693e-02,
          2.0008e-02, -2.9117e-02,  2.7826e-02,  4.8154e-02,  1.7746e-03,
         -1.8917e-02, -2.5676e-02, -7.2911e-02,  7.0312e-02, -6.1553e-02]],
       requires_grad=True)

In [ ]:
loss = l(input).sum()
loss.backward()

In [ ]:
l.linear.weight.grad

In [ ]:
l.lora_a.weight.grad

tensor([[-8.1828e-03,  4.9226e-01,  4.5623e-01,  1.9899e+00,  1.6879e+00,
         -1.9900e+00, -3.2140e-01, -1.4786e+00,  3.0771e-01, -1.3105e+00,
          2.0064e-01, -1.3550e+00, -9.1581e-01, -8.8062e-01,  5.4165e-01,
         -4.0654e-02, -1.3720e-01, -1.5575e+00,  3.1574e-01,  7.2257e-01,
          5.0164e-01, -1.3442e+00, -2.3309e+00, -1.1975e+00,  1.4308e+00,
          1.3442e+00, -8.7149e-01,  7.7565e-01,  4.5282e-01, -3.5017e-02,
         -4.0866e-02, -1.3587e-03,  6.7595e-01, -4.5002e-01, -6.1100e-01,
          4.9539e-01, -5.5540e-01,  4.2137e-01,  1.7584e+00, -4.9727e-01,
         -2.0213e-01, -3.3578e-02, -2.2678e+00,  2.6418e+00,  2.1101e+00,
          1.3789e+00,  1.5920e+00,  7.1215e-01,  3.0881e-01,  4.2541e-01,
          6.8200e-01,  6.3039e-01, -1.6429e-01,  2.1614e+00, -1.8808e+00,
         -7.9946e-01,  2.2911e-01, -9.1722e-01, -9.2038e-01, -1.0207e+00,
          1.2892e-01,  4.8746e-01,  2.1995e-01, -2.1877e+00,  9.7951e-01,
         -1.1843e+00,  2.3111e-01, -3.4901e-01,  3.9957e-01, -4.7889e-01,
         -2.7697e-01, -2.6254e-01, -4.8867e-01,  1.7777e-01, -2.3161e-01,
         -1.2224e-01, -9.4630e-01,  5.3084e-01, -1.6239e+00,  1.2839e-01,
         -2.2564e-01,  1.7583e+00, -3.3542e-01,  9.6335e-01, -1.2048e+00,
         -6.0322e-01,  2.6368e+00, -1.3213e-01,  6.2888e-01,  6.4340e-01,
          2.0397e+00,  2.2228e+00,  1.2737e+00, -1.3751e+00, -6.9864e-01,
          1.2932e+00, -3.7321e-01, -1.2414e-01,  4.2582e-02, -1.1689e+00],
        [-6.5804e-04,  3.9586e-02,  3.6688e-02,  1.6002e-01,  1.3573e-01,
         -1.6003e-01, -2.5846e-02, -1.1891e-01,  2.4745e-02, -1.0538e-01,
          1.6135e-02, -1.0896e-01, -7.3646e-02, -7.0816e-02,  4.3557e-02,
         -3.2693e-03, -1.1033e-02, -1.2525e-01,  2.5391e-02,  5.8107e-02,
          4.0340e-02, -1.0810e-01, -1.8744e-01, -9.6296e-02,  1.1506e-01,
          1.0810e-01, -7.0082e-02,  6.2374e-02,  3.6414e-02, -2.8160e-03,
         -3.2863e-03, -1.0925e-04,  5.4357e-02, -3.6189e-02, -4.9134e-02,
          3.9837e-02, -4.4663e-02,  3.3885e-02,  1.4140e-01, -3.9988e-02,
         -1.6255e-02, -2.7002e-03, -1.8237e-01,  2.1244e-01,  1.6969e-01,
          1.1089e-01,  1.2802e-01,  5.7269e-02,  2.4833e-02,  3.4210e-02,
          5.4844e-02,  5.0693e-02, -1.3212e-02,  1.7381e-01, -1.5125e-01,
         -6.4290e-02,  1.8424e-02, -7.3759e-02, -7.4014e-02, -8.2079e-02,
          1.0367e-02,  3.9199e-02,  1.7688e-02, -1.7592e-01,  7.8768e-02,
         -9.5237e-02,  1.8585e-02, -2.8066e-02,  3.2132e-02, -3.8511e-02,
         -2.2273e-02, -2.1112e-02, -3.9297e-02,  1.4296e-02, -1.8625e-02,
         -9.8303e-03, -7.6098e-02,  4.2688e-02, -1.3059e-01,  1.0324e-02,
         -1.8145e-02,  1.4139e-01, -2.6973e-02,  7.7469e-02, -9.6887e-02,
         -4.8508e-02,  2.1204e-01, -1.0625e-02,  5.0572e-02,  5.1739e-02,
          1.6402e-01,  1.7875e-01,  1.0242e-01, -1.1058e-01, -5.6182e-02,
          1.0400e-01, -3.0012e-02, -9.9830e-03,  3.4242e-03, -9.4001e-02],
        [ 1.3032e-02, -7.8400e-01, -7.2662e-01, -3.1692e+00, -2.6882e+00,
          3.1693e+00,  5.1188e-01,  2.3550e+00, -4.9007e-01,  2.0872e+00,
         -3.1955e-01,  2.1580e+00,  1.4586e+00,  1.4025e+00, -8.6266e-01,
          6.4748e-02,  2.1851e-01,  2.4805e+00, -5.0287e-01, -1.1508e+00,
         -7.9894e-01,  2.1409e+00,  3.7123e+00,  1.9072e+00, -2.2787e+00,
         -2.1409e+00,  1.3880e+00, -1.2353e+00, -7.2119e-01,  5.5770e-02,
          6.5085e-02,  2.1638e-03, -1.0766e+00,  7.1673e-01,  9.7311e-01,
         -7.8898e-01,  8.8455e-01, -6.7110e-01, -2.8005e+00,  7.9198e-01,
          3.2193e-01,  5.3478e-02,  3.6119e+00, -4.2074e+00, -3.3607e+00,
         -2.1961e+00, -2.5354e+00, -1.1342e+00, -4.9183e-01, -6.7753e-01,
         -1.0862e+00, -1.0040e+00,  2.6166e-01, -3.4423e+00,  2.9954e+00,
          1.2733e+00, -3.6490e-01,  1.4608e+00,  1.4659e+00,  1.6256e+00,
         -2.0532e-01, -7.7635e-01, -3.5031e-01,  3.4842e+00, -1.5600e+00,
          1.8862e+00, -3.6808e-01,  5.5585e-01, -6.3638e-01,  7.6271e-01,
          4.4111e-01,  4.1814e-01,  7.7829e-01, -2.8313e-01,  3.6887e-01,
          1.9469e-01,  1.5071e+00, -8.4544e-01,  2.5863e+00, -2.0447e-01,
          3.5937e-01, -2.8003e+00,  5.3421e-01, -1.5343e+00,  1.9189e+00,
          9.6072e-01, -4.1995e+00,  2.1043e-01, -1.0016e+00, -1.0247e+00,
         -3.2485e+00, -3.5402e+00, -2.0285e+00,  2.1900e+00,  1.1127e+00,
         -2.0597e+00,  5.9439e-01,  1.9772e-01, -6.7818e-02,  1.8617e+00],
        [ 1.7041e-02, -1.0252e+00, -9.5013e-01, -4.1440e+00, -3.5151e+00,
          4.1442e+00,  6.6934e-01,  3.0793e+00, -6.4081e-01,  2.7292e+00,
         -4.1785e-01,  2.8218e+00,  1.9072e+00,  1.8339e+00, -1.1280e+00,
          8.4665e-02,  2.8572e-01,  3.2435e+00, -6.5755e-01, -1.5048e+00,
         -1.0447e+00,  2.7994e+00,  4.8542e+00,  2.4938e+00, -2.9797e+00,
         -2.7994e+00,  1.8149e+00, -1.6153e+00, -9.4303e-01,  7.2926e-02,
          8.5105e-02,  2.8295e-03, -1.4077e+00,  9.3719e-01,  1.2724e+00,
         -1.0317e+00,  1.1566e+00, -8.7753e-01, -3.6619e+00,  1.0356e+00,
          4.2095e-01,  6.9928e-02,  4.7229e+00, -5.5016e+00, -4.3944e+00,
         -2.8717e+00, -3.3153e+00, -1.4831e+00, -6.4312e-01, -8.8594e-01,
         -1.4203e+00, -1.3128e+00,  3.4214e-01, -4.5012e+00,  3.9168e+00,
          1.6649e+00, -4.7714e-01,  1.9102e+00,  1.9168e+00,  2.1256e+00,
         -2.6848e-01, -1.0152e+00, -4.5806e-01,  4.5560e+00, -2.0399e+00,
          2.4664e+00, -4.8130e-01,  7.2683e-01, -8.3213e-01,  9.9732e-01,
          5.7680e-01,  5.4676e-01,  1.0177e+00, -3.7022e-01,  4.8234e-01,
          2.5458e-01,  1.9707e+00, -1.1055e+00,  3.3818e+00, -2.6737e-01,
          4.6991e-01, -3.6617e+00,  6.9853e-01, -2.0062e+00,  2.5091e+00,
          1.2562e+00, -5.4913e+00,  2.7516e-01, -1.3097e+00, -1.3399e+00,
         -4.2477e+00, -4.6292e+00, -2.6525e+00,  2.8637e+00,  1.4550e+00,
         -2.6932e+00,  7.7723e-01,  2.5853e-01, -8.8679e-02,  2.4344e+00],
        [-3.2355e-03,  1.9464e-01,  1.8039e-01,  7.8679e-01,  6.6739e-01,
         -7.8683e-01, -1.2708e-01, -5.8465e-01,  1.2167e-01, -5.1816e-01,
          7.9332e-02, -5.3574e-01, -3.6211e-01, -3.4819e-01,  2.1417e-01,
         -1.6074e-02, -5.4247e-02, -6.1582e-01,  1.2484e-01,  2.8570e-01,
          1.9835e-01, -5.3150e-01, -9.2163e-01, -4.7347e-01,  5.6572e-01,
          5.3150e-01, -3.4458e-01,  3.0669e-01,  1.7904e-01, -1.3846e-02,
         -1.6158e-02, -5.3720e-04,  2.6727e-01, -1.7794e-01, -2.4159e-01,
          1.9587e-01, -2.1960e-01,  1.6661e-01,  6.9525e-01, -1.9662e-01,
         -7.9922e-02, -1.3277e-02, -8.9669e-01,  1.0445e+00,  8.3433e-01,
          5.4522e-01,  6.2945e-01,  2.8158e-01,  1.2210e-01,  1.6821e-01,
          2.6966e-01,  2.4925e-01, -6.4959e-02,  8.5460e-01, -7.4365e-01,
         -3.1610e-01,  9.0590e-02, -3.6266e-01, -3.6392e-01, -4.0357e-01,
          5.0973e-02,  1.9274e-01,  8.6968e-02, -8.6500e-01,  3.8729e-01,
         -4.6827e-01,  9.1380e-02, -1.3800e-01,  1.5799e-01, -1.8935e-01,
         -1.0951e-01, -1.0381e-01, -1.9322e-01,  7.0291e-02, -9.1577e-02,
         -4.8334e-02, -3.7416e-01,  2.0989e-01, -6.4208e-01,  5.0763e-02,
         -8.9218e-02,  6.9521e-01, -1.3262e-01,  3.8091e-01, -4.7638e-01,
         -2.3851e-01,  1.0426e+00, -5.2242e-02,  2.4866e-01,  2.5440e-01,
          8.0648e-01,  8.7890e-01,  5.0361e-01, -5.4370e-01, -2.7624e-01,
          5.1134e-01, -1.4757e-01, -4.9085e-02,  1.6837e-02, -4.6219e-01]])

Fine-tune BERT model

In [ ]:
!pip install loralib
!pip install datasets
!pip install transformers[sentencepiece]
!pip install evaluate

Collecting loralib
  Downloading loralib-0.1.2-py3-none-any.whl.metadata (15 kB)
Downloading loralib-0.1.2-py3-none-any.whl (10 kB)
Installing collected packages: loralib
Successfully installed loralib-0.1.2
Requirement already satisfied: datasets in /usr/local/lib/python3.11/dist-packages (3.4.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets) (3.17.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.11/dist-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2024.12.0,>=2023.1.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<=2024.12.0,>=2023.1.0->datasets) (2024.10.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets) (3.11.13)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (0.3.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.18.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: transformers[sentencepiece] in /usr/local/lib/python3.11/dist-packages (4.45.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers[sentencepiece]) (3.17.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /usr/local/lib/python3.11/dist-packages (from transformers[sentencepiece]) (0.28.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers[sentencepiece]) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers[sentencepiece]) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers[sentencepiece]) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers[sentencepiece]) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers[sentencepiece]) (2.32.3)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from transformers[sentencepiece]) (0.5.3)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /usr/local/lib/python3.11/dist-packages (from transformers[sentencepiece]) (0.20.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers[sentencepiece]) (4.67.1)
Requirement already satisfied: protobuf in /usr/local/lib/python3.11/dist-packages (from transformers[sentencepiece]) (4.25.6)
Requirement already satisfied: sentencepiece!=0.1.92,>=0.1.91 in /usr/local/lib/python3.11/dist-packages (from transformers[sentencepiece]) (0.2.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers[sentencepiece]) (2024.10.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers[sentencepiece]) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers[sentencepiece]) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers[sentencepiece]) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers[sentencepiece]) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers[sentencepiece]) (2025.1.31)
Requirement already satisfied: evaluate in /usr/local/lib/python3.11/dist-packages (0.4.3)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from evaluate) (3.4.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.11/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.32.3)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.11/dist-packages (from evaluate) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from evaluate) (3.5.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.11/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2024.10.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from evaluate) (0.28.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from evaluate) (24.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (3.17.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (3.11.13)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (6.0.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2025.1)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (0.3.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.18.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)

In [ ]:
import numpy as np
import loralib as lora
import torchvision.models as models
import torch.nn.functional as F
import torch
from torch import nn
from matplotlib import pyplot as plt
from transformers import AutoModelForSequenceClassification, AutoTokenizer, TrainingArguments, Trainer
from datasets import load_dataset

In [ ]:
def linear_to_lora_linear(linear, r=6):
    bias = linear.bias is not None
    lora_layer = lora.Linear(
        in_features=linear.in_features,
        out_features=linear.out_features,
        bias=bias,
        #rank
        r=r,
    )

    lora_layer.weight = nn.Parameter(linear.weight.detach())

    if bias:
        lora_layer.bias = nn.Parameter(linear.bias.detach())

    return lora_layer


def to_lora(model, r=6):
    if isinstance(model, nn.ModuleList) or isinstance(model, nn.Sequential):
        for i, elem in enumerate(model):
            if isinstance(model[i], nn.Linear):
                model[i] = linear_to_lora_linear(model[i], r)
            else:
                if isinstance(model, nn.Module):
                    to_lora(model[i])

    else:
        for key in dir(model):
            attr = getattr(model, key)
            if attr is model:
              continue
            if isinstance(attr, nn.Linear):
                setattr(model, key, linear_to_lora_linear(attr, r))
                continue
            if not isinstance(attr, nn.Module):
                continue

            to_lora(attr)

In [ ]:
from datasets import DatasetDict
dataset = load_dataset('tweet_eval', 'irony')

model_name = 'bert-base-cased'
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)
model = model.cuda()
to_lora(model)
tokenizer = AutoTokenizer.from_pretrained(model_name)
datasets = dataset.map(lambda d: tokenizer(d['text'], truncation=True, padding=True), batched=True)

train-00000-of-00001.parquet:   0%|          | 0.00/183k [00:00<?, ?B/s]

test-00000-of-00001.parquet:   0%|          | 0.00/54.0k [00:00<?, ?B/s]

validation-00000-of-00001.parquet:   0%|          | 0.00/61.1k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/2862 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/784 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/955 [00:00<?, ? examples/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/436M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/transformers/modeling_utils.py:4779: FutureWarning: `_is_quantized_training_enabled` is going to be deprecated in transformers 4.39.0. Please use `model.hf_quantizer.is_trainable` instead
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

Map:   0%|          | 0/2862 [00:00<?, ? examples/s]

Map:   0%|          | 0/784 [00:00<?, ? examples/s]

Map:   0%|          | 0/955 [00:00<?, ? examples/s]

In [ ]:
args = TrainingArguments(
    'lora_bert',
    evaluation_strategy = 'epoch',
    save_strategy = 'no',
    load_best_model_at_end=False,
    weight_decay=0,
    report_to='none',
    learning_rate=5e-3,
    metric_for_best_model='f1',
    gradient_accumulation_steps=1,
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
)

import evaluate
metric = evaluate.load('f1')

def compute_metrics(pred):
    logits, labels = pred
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels, average='micro')

/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1545: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Downloading builder script:   0%|          | 0.00/6.79k [00:00<?, ?B/s]

In [ ]:
trainer = Trainer(
    model,
    args,
    train_dataset=datasets['train'],
    eval_dataset=datasets['validation'],
    tokenizer=tokenizer,
    compute_metrics=compute_metrics
)
trainer.train()

TrainOutput(global_step=537, training_loss=0.8912325740082526, metrics={'train_runtime': 181.4264, 'train_samples_per_second': 47.325, 'train_steps_per_second': 2.96, 'total_flos': 1388377756045944.0, 'train_loss': 0.8912325740082526, 'epoch': 3.0})

Llama + LoRA is implemented in library. It is possible to import it

In [ ]:
!pip install torchtune
!pip install torchao

Collecting torchtune
  Downloading torchtune-0.5.0-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: datasets in /usr/local/lib/python3.11/dist-packages (from torchtune) (3.4.1)
Requirement already satisfied: huggingface_hub[hf_transfer] in /usr/local/lib/python3.11/dist-packages (from torchtune) (0.28.1)
Requirement already satisfied: safetensors in /usr/local/lib/python3.11/dist-packages (from torchtune) (0.5.3)
Requirement already satisfied: kagglehub in /usr/local/lib/python3.11/dist-packages (from torchtune) (0.3.10)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.11/dist-packages (from torchtune) (0.2.0)
Collecting tiktoken (from torchtune)
  Downloading tiktoken-0.9.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Collecting blobfile>=2 (from torchtune)
  Downloading blobfile-3.0.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from torchtune) (2.0.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from torchtune) (4.67.1)
Collecting omegaconf (from torchtune)
  Downloading omegaconf-2.3.0-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from torchtune) (5.9.5)
Requirement already satisfied: Pillow>=9.4.0 in /usr/local/lib/python3.11/dist-packages (from torchtune) (11.1.0)
Collecting pycryptodomex>=3.8 (from blobfile>=2->torchtune)
  Downloading pycryptodomex-3.22.0-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
Requirement already satisfied: urllib3<3,>=1.25.3 in /usr/local/lib/python3.11/dist-packages (from blobfile>=2->torchtune) (2.3.0)
Requirement already satisfied: lxml>=4.9 in /usr/local/lib/python3.11/dist-packages (from blobfile>=2->torchtune) (5.3.1)
Requirement already satisfied: filelock>=3.0 in /usr/local/lib/python3.11/dist-packages (from blobfile>=2->torchtune) (3.17.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets->torchtune) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from datasets->torchtune) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets->torchtune) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.11/dist-packages (from datasets->torchtune) (2.32.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from datasets->torchtune) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.11/dist-packages (from datasets->torchtune) (0.70.16)
Requirement already satisfied: fsspec<=2024.12.0,>=2023.1.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<=2024.12.0,>=2023.1.0->datasets->torchtune) (2024.10.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets->torchtune) (3.11.13)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from datasets->torchtune) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets->torchtune) (6.0.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub[hf_transfer]->torchtune) (4.12.2)
Collecting hf-transfer>=0.1.4 (from huggingface_hub[hf_transfer]->torchtune)
  Downloading hf_transfer-0.1.9-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.7 kB)
Collecting antlr4-python3-runtime==4.9.* (from omegaconf->torchtune)
  Downloading antlr4-python3-runtime-4.9.3.tar.gz (117 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.0/117.0 kB 7.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.11/dist-packages (from tiktoken->torchtune) (2024.11.6)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets->torchtune) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets->torchtune) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets->torchtune) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets->torchtune) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets->torchtune) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets->torchtune) (0.3.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets->torchtune) (1.18.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets->torchtune) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets->torchtune) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets->torchtune) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets->torchtune) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets->torchtune) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets->torchtune) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets->torchtune) (1.17.0)
Downloading torchtune-0.5.0-py3-none-any.whl (810 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 810.3/810.3 kB 30.3 MB/s eta 0:00:00
Downloading blobfile-3.0.0-py3-none-any.whl (75 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.4/75.4 kB 6.6 MB/s eta 0:00:00
Downloading omegaconf-2.3.0-py3-none-any.whl (79 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 7.7 MB/s eta 0:00:00
Downloading tiktoken-0.9.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 58.0 MB/s eta 0:00:00
Downloading hf_transfer-0.1.9-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 81.8 MB/s eta 0:00:00
Downloading pycryptodomex-3.22.0-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 74.2 MB/s eta 0:00:00
Building wheels for collected packages: antlr4-python3-runtime
  Building wheel for antlr4-python3-runtime (setup.py) ... done
  Created wheel for antlr4-python3-runtime: filename=antlr4_python3_runtime-4.9.3-py3-none-any.whl size=144555 sha256=ec3cfa4d5af5d2a5aebcbcb0cbbf2f3663c0420922c9d88ee5a145e3090b6470
  Stored in directory: /root/.cache/pip/wheels/1a/97/32/461f837398029ad76911109f07047fde1d7b661a147c7c56d1
Successfully built antlr4-python3-runtime
Installing collected packages: antlr4-python3-runtime, pycryptodomex, omegaconf, hf-transfer, tiktoken, blobfile, torchtune
Successfully installed antlr4-python3-runtime-4.9.3 blobfile-3.0.0 hf-transfer-0.1.9 omegaconf-2.3.0 pycryptodomex-3.22.0 tiktoken-0.9.0 torchtune-0.5.0

Collecting torchao
  Downloading torchao-0.9.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_28_x86_64.whl.metadata (14 kB)
Downloading torchao-0.9.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_28_x86_64.whl (5.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 63.0 MB/s eta 0:00:00
Installing collected packages: torchao
Successfully installed torchao-0.9.0

In [ ]:
from torchtune.models.llama2 import llama2_7b, lora_llama2_7b

lora_model = lora_llama2_7b(lora_attn_modules=["q_proj", "k_proj", "v_proj", "output_proj"])

In [ ]:
from torchtune.modules.peft.peft_utils import get_adapter_params, set_trainable_params


lora_params = get_adapter_params(lora_model)

set_trainable_params(lora_model, lora_params)

total_params = sum([p.numel() for p in lora_model.parameters()])
trainable_params = sum([p.numel() for p in lora_model.parameters() if p.requires_grad])
print(
  f"""
  {total_params} total params,
  {trainable_params}" trainable params,
  {(100.0 * trainable_params / total_params):.2f}% of all params are trainable.
  """
)

Train using tune:

In [ ]:
!tune run --nnodes 1 --nproc_per_node 2 lora_finetune_distributed --config llama2/7B_lora

## Sources

https://github.com/philschmid/knowledge-distillation-transformers-pytorch-sagemaker/blob/master/knowledge-distillation.ipynb

https://github.com/bayesgroup/HSE_ML_research_seminar/blob/master/2021-2022/182/11%20-%20LoRA/lora.ipynb

https://pytorch.org/torchtune/0.4/tutorials/lora_finetune.html